name: Auto-assign on Label

on:
  issues:
    types: [labeled]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign to Developer for Bug
        if: contains(github.event.label.name, 'bug')
        uses: actions-ecosystem/action-assign-issue@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: "username"