name: Auto-assign user from issue label

on:
  issues:
    types: [opened, edited]

jobs:
  label-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Add Bug Label
        if: contains(github.event.issue.title, 'bug')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "bug"