name: Track Dependencies

on:
  issues:
    types: [opened, edited]

jobs:
  add-dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Add Dependency Label
        if: contains(github.event.issue.body, '#dependent-on')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "dependency"