name: Update Issue Status

on:
  pull_request:
    types: [closed]

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Update Issue Status to "Done"
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Correct input for the token
          issue-number: ${{ github.event.issue.number }}
          body: "Status: Done"
